// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-sF4mmIUjfbwSLzLxJRAXrjbCcW4HmC8',
    appId: '1:110505923172:web:77a86ed99ff6ab1f900571',
    messagingSenderId: '110505923172',
    projectId: 'health-passport-575ea',
    authDomain: 'health-passport-575ea.firebaseapp.com',
    storageBucket: 'health-passport-575ea.firebasestorage.app',
    measurementId: 'G-NRTS7KXNSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZR6meNCzNlD8djnLuVdH9AnqnSOWHfc',
    appId: '1:110505923172:android:89fcd3b3509256ea900571',
    messagingSenderId: '110505923172',
    projectId: 'health-passport-575ea',
    storageBucket: 'health-passport-575ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoVcIja_YXn7wUqc9Q45CX-Q_oqY1wQ4',
    appId: '1:110505923172:ios:d8c6068fa8295172900571',
    messagingSenderId: '110505923172',
    projectId: 'health-passport-575ea',
    storageBucket: 'health-passport-575ea.firebasestorage.app',
    iosBundleId: 'com.example.healthpassport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANoVcIja_YXn7wUqc9Q45CX-Q_oqY1wQ4',
    appId: '1:110505923172:ios:d8c6068fa8295172900571',
    messagingSenderId: '110505923172',
    projectId: 'health-passport-575ea',
    storageBucket: 'health-passport-575ea.firebasestorage.app',
    iosBundleId: 'com.example.healthpassport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-sF4mmIUjfbwSLzLxJRAXrjbCcW4HmC8',
    appId: '1:110505923172:web:dd29caed3ae35928900571',
    messagingSenderId: '110505923172',
    projectId: 'health-passport-575ea',
    authDomain: 'health-passport-575ea.firebaseapp.com',
    storageBucket: 'health-passport-575ea.firebasestorage.app',
    measurementId: 'G-65VXCVQ693',
  );
}
